### ISSUE TITLE
PASSWORD_EXPIRE_FORCE doesn't work

### ISSUE THREAD

**Issue by eyk107** [cash/django-password-expire#1]
Hi,

when setting PASSWORD_EXPIRE_FORCE to 'True' no redirection is happening after logging in with an expired password.
My Django-version is 3.2.14

Thank you for your help.
Best regards
Eyk

**Comment by hansonec** [comment]
I am running Django 3.2.16 and have no issue with PASSWORD_EXPIRE_FORCE. Keep in mind it's only for newly created users. I successfully:
1. created a new user
2. logged in as the new user
3. got redirected to change password
4. changed the password

**Comment by roymeli** [comment]
> Hi,
> 
> when setting PASSWORD_EXPIRE_FORCE to 'True' no redirection is happening after logging in with an expired password. My Django-version is 3.2.14
> 
> Thank you for your help. Best regards Eyk

I got the same problem too... 
I would like to get some help :) 
Roy

**Comment by cash** [comment]
@roymeli I just tested this and this works as expected. From the README:
```
To redirect new users to the change password page, set this flag in the settings:

PASSWORD_EXPIRE_FORCE = True
```
This setting forces new users to change their passwords. This setting is *only* for new users. If you have a Django site with this package configured, you should be able to create a new user and then login as this new user and get redirected to the password change page.

I'm closing this issue. If you are having a problem with this package, please open a new issue, describe what you expect should happen and then describe what actually happens.
